import { CHARACTER_IDS, SKIN_IDS } from "./ids";
import { SKIN_CONFIG } from "./skinConfig";

/** Dados estáveis para upsert no seed / ensureCatalog. */
export const CATALOG_CHARACTERS = [
  {
    id: CHARACTER_IDS.nyx,
    slug: "nyx",
    name: "Nyx",
    description: "Provocadora, elegante e perigosamente observadora.",
    personalityKey: "nyx",
    defaultUnlocked: true,
    active: true,
    displayOrder: 1,
  },
  {
    id: CHARACTER_IDS.eva,
    slug: "eva",
    name: "Eva",
    description: "Simpática, carinhosa e inteligente — ainda assim vai notar onde você gastou.",
    personalityKey: "eva",
    defaultUnlocked: false,
    active: true,
    displayOrder: 2,
  },
] as const;

export const CATALOG_SKINS = [
  {
    id: SKIN_IDS.nyxDefault,
    characterId: CHARACTER_IDS.nyx,
    slug: "nyx-default",
    name: "Nyx",
    description: "Provocadora, elegante e perigosamente observadora.",
    assetConfig: SKIN_CONFIG["nyx-default"].assets,
    defaultUnlocked: true,
    isDefault: true,
    active: true,
    displayOrder: 1,
    availabilityStatus: "available" as const,
    unlockRuleKey: null as string | null,
  },
  {
    id: SKIN_IDS.evaDefault,
    characterId: CHARACTER_IDS.eva,
    slug: "eva-default",
    name: "Eva",
    description: "Simpática, carinhosa e inteligente — ainda assim vai notar onde você gastou.",
    assetConfig: SKIN_CONFIG["eva-default"].assets,
    defaultUnlocked: false,
    isDefault: true,
    active: true,
    displayOrder: 2,
    availabilityStatus: "locked" as const,
    unlockRuleKey: "journey_missions_3",
  },
  {
    id: SKIN_IDS.nyxBeach,
    characterId: CHARACTER_IDS.nyx,
    slug: "nyx-beach",
    name: "Nyx Praia",
    description: "A Nyx também precisa fingir que sabe descansar.",
    assetConfig: SKIN_CONFIG["nyx-beach"].assets,
    defaultUnlocked: false,
    isDefault: false,
    active: true,
    displayOrder: 3,
    availabilityStatus: "locked" as const,
    unlockRuleKey: "journey_collection_1_complete",
  },
  {
    id: SKIN_IDS.evaFitness,
    characterId: CHARACTER_IDS.eva,
    slug: "eva-fitness",
    name: "Boa noite Eva",
    description: "Uma versão mais noturna, elegante e acolhedora da Eva.",
    assetConfig: SKIN_CONFIG["eva-fitness"].assets,
    defaultUnlocked: false,
    isDefault: false,
    active: true,
    displayOrder: 4,
    availabilityStatus: "locked" as const,
    unlockRuleKey: "journey_eva_fitness_pending",
  },
] as const;
